### ISSUE TITLE
da2 connection issues

### ISSUE THREAD

**Issue by tuckermiles70** [fdac20/TwitterSentiment#17]
@audrism 

I'm having issues connecting to da2 at the moment, and I'm not too sure about what's going on. Any help would be appreciated!

![image](https://user-images.githubusercontent.com/43181231/98300489-57dbca00-1f87-11eb-98e2-9b449a316029.png)

I'm no longer able to access via "ssh da2" but the second command does let me in as shown above.

**Comment by audrism** [comment]
Are you sure you are using:
ssh -p3099 -L3000:localhost:3000 yournetid@da2.eecs.utk.edu

**Comment by tuckermiles70** [comment]
That allows me to connect, but I can't connect to my notebook via "http://localhost:8888/" like I was previously able to with just "ssh da2." 

This is my ssh config on my local machine:
![image](https://user-images.githubusercontent.com/43181231/98375872-bac57380-2010-11eb-90e8-9e9c14470b4a.png)

**Comment by audrism** [comment]
The notebook is in a separate container, so you need to run another ssh (as for part A) to connect to the notebook.Your home folders will be the same, however.
