### ISSUE TITLE
Determine base user groups for non-University accounts

### ISSUE THREAD

**Issue by tuckermiles70** [fdac20/TwitterSentiment#4]

**Comment by tuckermiles70** [comment]
Collect tweets with keywords via snscrape
Assuming there will be duplicates, leave them in csvs, but remove with dataframe processing
remove any tweets from other dataset from here

**Comment by vickit144** [comment]
**Keywords:** **UTK**, **utknoxville**, utknox, vols, VFL, volmeansall, bigorange, rockytop, gbo, gobigorange, volunteers, govols, tennessevols, **university of tennessee**
 
https://github.com/Mottl/GetOldTweets3/issues/98
